const fs = require('fs')
const b = fs.readFileSync('dist/project.config.json')
const m = b.toString('utf8').match(/"description":\s*"([^"]*)"/)
console.log('dist description:', JSON.stringify(m && m[1]))
const b2 = fs.readFileSync('project.config.json')
const m2 = b2.toString('utf8').match(/"description":\s*"([^"]*)"/)
console.log('root description:', JSON.stringify(m2 && m2[1]))
const app = JSON.parse(fs.readFileSync('dist/app.json', 'utf8'))
console.log('app.window:', JSON.stringify(app.window))
