export default defineAppConfig({
  // React custom-tab-bar is not supported by the Skyline renderer yet.
  renderer: 'webview',
  pages: [
    'pages/chat/index',
    'pages/plans/index',
    'pages/blog/index',
    'pages/profile/index',
    'pages/login/index',
    'pages/scan-login/index',
    'pages/blog-detail/index',
    'pages/plan-detail/index',
    'pages/plan-create/index',
    'pages/publish/index',
    'pages/blog-manage/index',
    'pages/points/index',
    'pages/subscription/index',
    'pages/notifications/index',
    'pages/account-settings/index',
    'pages/account-profile/index',
    'pages/security-center/index',
    'pages/recitation/index',
    'pages/recitation-practice/index',
    'pages/recitation-report/index',
    'pages/recitation-history/index',
  ],
  tabBar: {
    custom: true,
    color: '#86909c',
    selectedColor: '#1677ff',
    backgroundColor: '#ffffff',
    borderStyle: 'white',
    list: [
      { pagePath: 'pages/chat/index', text: '对话' },
      { pagePath: 'pages/plans/index', text: '计划' },
      { pagePath: 'pages/blog/index', text: '博客' },
      { pagePath: 'pages/profile/index', text: '我的' },
    ],
  },
  window: {
    navigationStyle: 'custom',
    navigationBarBackgroundColor: '#ffffff',
    navigationBarTextStyle: 'black',
    backgroundColor: '#ffffff',
    backgroundTextStyle: 'dark',
  },
})
